### ISSUE TITLE
prev() seems slow

### ISSUE THREAD

**Issue by btyukodi** [bobbaluba/rlcg#1]
Thanks for sharing this code!
I managed to write a Python wrapper around it. It seems, however that the prev() generator is much, much slower than the next(). Is that to be expected? Any chance to make it faster?...

Thanks a lot,
Botond

**Comment by johanhelsing** [comment]
Stange... Looking at the code i would expect it to be very similar.

```
unsigned int next() {
        //nextx = (a * x + c) % m;
        x = (A * x + C) & (M - 1);
        return x >> D;
    }
    unsigned int prev() {
        const uint64_t ainverse = extendedEuclidX(A, M);
        //prevx = (ainverse * (x - c)) mod m
        x = ainverse * (x - C) & (M - 1);
        return x >> D;
    }
```

Ainverse should be calculated at compile time. Otherwise it's just one multiplication, one addition/subtraction, one bitwise and, and one bitshift.

Are you sure you are compiling with optimisations enabled?

**Comment by btyukodi** [comment]
Thanks for your answer. I guess you're right. I have just tested the benchmark and it worked fine. I'm not very good at C++ and I must have messed up something when trying to make it work with Python's boost. To make it simpler, I removed the namespaces and the template, maybe that could have changed something... Anyway, I attach the code I have, maybe you can spot something obvious right away.

Thanks,
Botond

[python_test.zip](https://github.com/bobbaluba/rlcg/files/1461825/python_test.zip)

**Comment by btyukodi** [comment]
Ok, looks like it was the template. It's weird that changing template parameters to constants increases runtime so much. Anyway, the following works:
[python_boost.zip](https://github.com/bobbaluba/rlcg/files/1467755/python_boost.zip)

I would have one more question though. After initializing the rng, `rng.next()` and after `rng.prev()` always ends up in zero:
`seed = 23124`
`rng = rlcg.ReversibleLCG(seed)`
`rng.next()`  <-- Ok, some random number
`rng.prev()` <-- always zero, independently of `seed`

I can imagine this would result in a quite biased distribution...

Thanks
Botond

**Comment by johanhelsing** [comment]
I'm at my phone, so can't look at your code, but when i wrote the template, i made sure ainverse was calculated at compile time, maybe that's your problem?

The zero before the starting position is a property of lcgs.

You may look at https://stackoverflow.com/questions/2911432/reversible-pseudo-random-sequence-generator if you need a different kind of distribution.

**Comment by btyukodi** [comment]
I see, it all makes sense now! I appreciate your help!
